[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vbench"
version = "0.1.6"
description = "Video generation benchmark"
readme = "README-pypi.md"
license = {text = "Apache Software License 2.0"}

requires-python = ">=3.8"
dependencies = [
    "Pillow",
    "numpy<2.0.0",
    "openai-clip",
    "setuptools",
    "easydict",
    "pyiqa",
    "omegaconf",
]

[project.urls]
Source = "https://github.com/Vchitect/VBench"

[project.scripts]
vbench = "vbench.cli.vbench:main"

[project.optional-dependencies]
dev = [
    "matplotlib",
    "timm>=0.9,<=1.0.12",
    "wheel",
    "cython",
    "tensorboard",
    "scipy",
    "opencv-python",
    "scikit-learn",
    "scikit-image",
    "decord",
    "requests",
    "pyyaml",
    "lvis",
    "fairscale>=0.4.4",
    "fvcore",
    "urllib3",
    "boto3",
    "transformers>=4.33.2",
    "pycocoevalcap",
]

detectron2 = [
    "detectron2 @ git+https://github.com/facebookresearch/detectron2.git"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["vbench*"]


[tool.setuptools.package-data]
"*" = ["*.json", "*.yaml", "*.yml", "*.txt", "*.md"]
